Update this file
dietpi-update update script fails with error ( mine @v76 )
------------------------------------
Error: Obtained server version value from github is invalid. Please try running dietpi-update again.
-----------------------------------
I think its because of 2 values ehre v77 and v4.. v4 is an error and should be removed.